version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: shortener-db
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener123
    ports:
      - "5432:5432"
    volumes:
      - shortener-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  shortener-data:

